### ISSUE TITLE
Unblock ENA assembly submissions

### ISSUE THREAD

**Issue by SamStudio8** [CLIMB-COVID/climb-covid-outbound-submissions#1]
i have got ENA assembly submissions flowing again, but as it is written it will only submit sequences where a sample (ERS) and run (ERR) accession exist in Majora.

we can sidestep this for the case of the run accession by [removing these lines](https://github.com/CLIMB-COVID/climb-covid-outbound-submissions/blob/master/ena/metadata_to_erz_csv.py#L26-L28). however webin-cli will require a pre-registered sample accession to work. naturally, webin-cli does not let you submit samples, so you'll have to do this another way.

we have the pieces to make this work as pyena [submits samples through XML API](https://github.com/SamStudio8/pyena/blob/master/pyena/client.py#L193-L208) before submitting a run. i would recommend forking `pyena` and offering a mode to turn off the run submission ([here](https://github.com/SamStudio8/pyena/blob/master/pyena/client.py#L328)) such that we have a mode of pyena just for submitting samples alone. this sample-only pyena will need to be integrated into the fancy new [ENA submission pipe](https://github.com/CLIMB-COVID/elan-ena-nextflow). you can use [the original BAM submission pipe](https://github.com/CLIMB-COVID/elan-nextflow/blob/stable/bam/dehuman-post.nf) for some inspiration.

**Comment by SamStudio8** [comment]
you'll also need to write a systemd service and timer -- use the tael_gisaid mqtt-client as guidance, the client will need to call the auto_submit_assembly.sh

**Comment by BioWilko** [comment]
I have a solution ready for testing based on the above suggestions:
1. I have [forked pyena](https://github.com/CLIMB-COVID/pyena/tree/no-submit-dev) and started a development branch for testing. To this I added a `--sample-only` mode to limit the functionality to just submitting the biosample to ENA via the XML API.
2. I have also added a [dev branch of elan-ena-nextflow](https://github.com/CLIMB-COVID/elan-ena-nextflow/tree/pyena-dev) which includes pyena and is ready for initial testing.

**Comment by BioWilko** [comment]
I have added a full set of test flags throughout the main pipeline and `auto_submit_assembly.sh`.
Submission is working to the ENA test endpoints and ocarina is talking to test-majora fine.

I will continue testing tomorrow AM but suspect I will be able to progress to production within 2 days.

**Comment by BioWilko** [comment]
The pipe is now running having passed all the tests I could throw at it, once it has submitted the samples in its trial by fire (71,443) I will mark this as finished.
